version: '3.8'

services:
    app:
      container_name: veiculo-app
      build: .
      ports: 
        - "8010:80"
      volumes:
        - ./:/usr/share/nginx
        - .docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - app-network
      hostname: docker.test

    db:
      container_name: postgres_container
      image: postgres:14.3-alpine
      restart: always
      environment:
        POSTGRES_DB: veiculo_db
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: secret
        #PGDATA: /var/lib/postgresql/data
      ports:
       - "5432:5432"
      #volumes:
      # - db-data:/var/lib/postgresql/data
      networks:
        - app-network

    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4:5.5
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: secret
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      #volumes:
       # - pgadmin-data:/var/lib/pgadmin
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
